name: build

on:
  push:
    tags:
        - version*
    branches: 
        - dev
        - master        
  pull_request:
    branches:
        - dev
        - master

jobs:
  build:

    runs-on: ubuntu-latest
    container: debian:sid

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test
      run: "sha1sum testdata/fla/cs3/0012_texts/Contents"
#      
#    - name: Set up JDK 8
#      uses: AdoptOpenJDK/install-jdk@v1
#      with:
#        version: '8'
#        architecture: x64
#        targets: 'JDK_8;JAVA_HOME'
#    - name: Set up ant
#      run: |
#        apt update -y -qq
#        apt install -y -qq ant 
#    - name: Build
#      run: "ant build"
#    - name: Test
#      run: "ant test"
